### ISSUE TITLE
Not compatible function hashToken with Moodle 3.9

### ISSUE THREAD

**Issue by TomoTsuyuki** [h5p/moodle-mod_hvp#379]
We are having an issue "Invalid security token" error with Moodle 3.9.

Probably related this:
https://tracker.moodle.org/browse/MDL-69415

I found our theme required '/backup/util/ui/renderer.php' and the file loaded all modules from the site.
Content bank H5P editor, which is using theme, tries to use hashToken function from plugin (moodle-mod_hvp) because of the reason above.
But the ajax function, which doesn't use theme, tries to use hashToken from moodle core (https://github.com/moodle/moodle/blob/MOODLE_39_STABLE/h5p/h5plib/v124/joubel/core/h5p.classes.php#L3220)

The source of issue is included file, but we can see different logic in hashToken function between core and plugin.
Plugin uses general h5p library which uses $_SESSION array, but Moodle core uses $SESSION object.
If it's same logic between core and plugin, at least the function works in our site.

Is that possible to use same logic in plugin as core?

**Comment by thomasmars** [comment]
Thanks for reporting this. 
I'm not sure why Moodle has changed the H5P core without changing the namespace. 

We can not use a global Moodle variable (`$SESSION`) in H5P core, as H5P core is used within multiple plugin integrations, e.g. for Moodle, Wordpress, Drupal ++, which would not be compatible with Moodle specific globals.

Ideally the code should be refactored to use a separate session service if an integration needed to implement a different solution for storing session variables. This has never been necessary for any of our plugin integrations, so that is why we use the php session directly in the core implementation.

**Comment by TomoTsuyuki** [comment]
Thanks for your comment.
We found a way to avoid loading all modules from Content bank H5P editor, so our issue is solved.
But it will happen when some functions/plugins loads mod_h5p module unexpectedly.
I understand the H5P core shouldn't change, and also should not affect between core and plugin session.
I will write a comment to Moodle tracker about that.
